#!/bin/bash
# ~/.bashrc


# General Settings
shopt -s cdspell
shopt -s histappend
export HISTCONTROL=ignoredups:ignorespace
export HISTIGNORE=ls:l:la:ll:lk:lt:lc:lu:cd:pwd
export GREP_OPTIONS='--color=auto'
export LS_OPTIONS='--color=auto'
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced
export LS_COLORS='di=36;1:fi=0:ln=95;1:pi=5:so=5:bd=5:cd=5:or=37:mi=0:ex=31;1:'
export EDITOR='vim'

# Plugins
configdir=~/.dotfiles
theme='kevlar'
source $configdir/themes/$theme.theme
for plugin in $(ls $configdir/plugins); do
    source $configdir/plugins/$plugin
done

# Augment PATH
[ -d ~/Applications ] && PATH=~/Applications:$PATH
[ -d ~/bin ] &&  PATH=~/bin:$PATH

# Aliases and Functions
alias l='ls -CF'        # multicolumn with suffixes for file type
alias la='ls -A'        # list all except ./ and ../
alias ll='ls -alFh'     # show  dot dirs, list long, w/ type suffix
alias lk='ls -lSrh'     # list long, sort size, largest last
alias lt='ls -ltrh'     # list long, sort time, by last modified, newest last
alias lc='ls -ltcrh'    # list long, sort time, by last changed, newest last
alias lu='ls -lturh'    # list long, sort time, by last access, newest last

function pyclean() { find . -name "*.py[co]" -delete; }

function command_exists() { type "$1" &> /dev/null; }

function ips() {
    ifconfig | grep "inet " | awk '{ print $2 }'
    local ip=$(curl -s checkip.dyndns.org | grep -Eo '[0-9\.]+' &)
    echo -e "WLAN IP: $ip"
}

function down4me() {
    curl -s "http://www.downforeveryoneorjustme.com/$1" \
        | sed '/just you/!d;s/<[^>]*>//g'
}

function extract () {
    if [ $# -ne 1 ]; then
        echo "Error: No file specified."
        return 1
    fi

    if [ -f $1 ] ; then
        case $1 in
            *.tar.bz2) tar xvjf $1   ;;
            *.tar.gz)  tar xvzf $1   ;;
            *.bz2)     bunzip2 $1    ;;
            *.rar)     unrar x $1    ;;
            *.gz)      gunzip $1     ;;
            *.tar)     tar xvf $1    ;;
            *.tbz2)    tar xvjf $1   ;;
            *.tgz)     tar xvzf $1   ;;
            *.zip)     unzip $1      ;;
            *.Z)       uncompress $1 ;;
            *.7z)      7z x $1       ;;
            *)         echo "'$1' cannot be extracted via extract" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

# Local Settings
[ -f ~/.profile.local ] && source ~/.profile.local

# Finally, Remove Duplicates From PATH
PATH=$(awk -v RS=':' '{ if (!arr[$0]++) {printf("%s%s",!ln++?"":":",$0)}}' <<< $PATH)
